package com.mygdx.game.entity.boss1;

public enum Boss1Input {
	LEFT_KEYDOWN, LEFT_KEYUP, RIGHT_KEYDOWN, RIGHT_KEYUP,
	SLAM_KEYDOWN, SLAM_KEYUP,
	EARTHQUAKE_KEYDOWN, EARTHQUAKE_KEYUP,
	ROLL_KEYDOWN, ROLL_KEYUP,
	CROWD_CONTROL
}
