package com.untitled.game.character;

/**
 * Enum of Assassin states.
 */
public enum AssassinStates {
	STANDING, STANDING_LEFT_RIGHT, WALKING_LEFT, WALKING_RIGHT,
	STANDING_UP, STANDING_UP_LEFT_RIGHT, WALKING_UP_LEFT, WALKING_UP_RIGHT,
	DASH, DASH_LEFT, DASH_RIGHT, DASH_LEFT_RIGHT,
	DASH_UP, DASH_UP_LEFT, DASH_UP_RIGHT, DASH_UP_LEFT_RIGHT,
	SHURIKEN_THROW, SHURIKEN_THROW_LEFT, SHURIKEN_THROW_RIGHT, SHURIKEN_THROW_LEFT_RIGHT,
	SHURIKEN_THROW_UP, SHURIKEN_THROW_UP_LEFT, SHURIKEN_THROW_UP_RIGHT, SHURIKEN_THROW_UP_LEFT_RIGHT,
	CLEANSE, CLEANSE_LEFT, CLEANSE_RIGHT, CLEANSE_LEFT_RIGHT,
	CLEANSE_UP, CLEANSE_UP_LEFT, CLEANSE_UP_RIGHT, CLEANSE_UP_LEFT_RIGHT
}
