package com.mygdx.game.screens.game.character;

public enum TankInput {
	LEFT_KEYDOWN, LEFT_KEYUP, RIGHT_KEYDOWN, RIGHT_KEYUP,
	BLOCK_KEYDOWN, BLOCK_INPUT, BLOCK_KEYUP,
	IMPALE_KEYDOWN, IMPALE_KEYUP,
	FORTRESS_KEYDOWN, FORTRESS_INPUT, FORTRESS_KEYUP,
	SWITCH_CHARACTER, CROWD_CONTROL
}
