package com.mygdx.game.entity.character;

public enum AssassinInput {
	LEFT_KEYDOWN, LEFT_KEYUP, RIGHT_KEYDOWN, RIGHT_KEYUP, UP_KEYDOWN, UP_KEYUP,
	BLOCK_KEYDOWN, BLOCK_KEYUP,
	IMPALE_KEYDOWN, IMPALE_KEYUP,
	FORTRESS_KEYDOWN, FORTRESS_KEYUP,
	SWITCH_CHARACTER
}
