package com.mygdx.game.entity.character;

public enum AssassinStates {
	STANDING, STANDING_LEFT_RIGHT, WALKING_LEFT, WALKING_RIGHT,
	STANDING_UP, STANDING_UP_LEFT_RIGHT, WALKING_UP_LEFT, WALKING_UP_RIGHT,
	PRIMARY, PRIMARY_LEFT, PRIMARY_RIGHT, PRIMARY_LEFT_RIGHT,
	PRIMARY_UP, PRIMARY_UP_LEFT, PRIMARY_UP_RIGHT, PRIMARY_UP_LEFT_RIGHT,
	SECONDARY, TERTIARY
}
