package com.mygdx.game.entity.character;

public enum AssassinInput {
	LEFT_KEYDOWN, LEFT_KEYUP, RIGHT_KEYDOWN, RIGHT_KEYUP, UP_KEYDOWN, UP_KEYUP,
	DASH_KEYDOWN, DASH_KEYUP,
	SHURIKEN_THROW_KEYDOWN, SHURIKEN_THROW_KEYUP,
	CLEANSE_KEYDOWN, CLEANSE_KEYUP,
	SWITCH_CHARACTER, CROWD_CONTROL
}
