package com.mygdx.game.entity.character;

public enum CharacterInput {
	LEFT_KEYDOWN, LEFT_KEYUP, RIGHT_KEYDOWN, RIGHT_KEYUP, UP_KEYDOWN, UP_KEYUP,
	PRIMARY_KEYDOWN, PRIMARY_KEYUP,
	SECONDARY_KEYDOWN, SECONDARY_KEYUP,
	TERTIARY_KEYDOWN, TERTIARY_KEYUP
}
