package com.mygdx.game.entity.character;

public enum TankStates {
	STANDING, WALKING_LEFT, WALKING_RIGHT, STANDING_LEFT_RIGHT,
	BLOCK, BLOCK_LEFT, BLOCK_RIGHT, BLOCK_LEFT_RIGHT,
	BLOCK_UP, BLOCK_UP_LEFT, BLOCK_UP_RIGHT, BLOCK_UP_LEFT_RIGHT,
	BLOCK_STANDING, BLOCK_WALKING_LEFT, BLOCK_WALKING_RIGHT, BLOCK_STANDING_LEFT_RIGHT,
	IMPALE, IMPALE_LEFT, IMPALE_RIGHT, IMPALE_LEFT_RIGHT,
	FORTRESS, FORTRESS_LEFT, FORTRESS_RIGHT, FORTRESS_LEFT_RIGHT,
	FORTRESS_STANDING, FORTRESS_WALKING_LEFT, FORTRESS_WALKING_RIGHT, FORTRESS_STANDING_LEFT_RIGHT,
	FORTRESS_BLOCK, FORTRESS_BLOCK_LEFT, FORTRESS_BLOCK_RIGHT, FORTRESS_BLOCK_LEFT_RIGHT,
	FORTRESS_IMPALE, FORTRESS_IMPALE_LEFT, FORTRESS_IMPALE_RIGHT, FORTRESS_IMPALE_LEFT_RIGHT
}
