package com.mygdx.game.entity.character;

public enum TankStates {
	STANDING, WALKING_LEFT, WALKING_RIGHT, STANDING_LEFT_RIGHT,
	PRIMARY, PRIMARY_LEFT, PRIMARY_RIGHT, PRIMARY_LEFT_RIGHT,
	SECONDARY, SECONDARY_LEFT, SECONDARY_RIGHT, SECONDARY_LEFT_RIGHT,
	TERTIARY
}
