package com.mygdx.game.assets;

public enum TextureName {
	BACKGROUND, FLOOR, STUNNED, WEAK_SPOT,
	BUTTON_NORMAL, BUTTON_HOVER, BUTTON_MENU_HOVER,
	HIGHSCORES_TITLE, HIGHSCORES_ODD, HIGHSCORES_EVEN,
	HEALTH_BAR_BACKGROUND, HEALTH_BAR_ASSASSIN, HEALTH_BAR_BOSS, HEALTH_BAR_TANK,
	COOLDOWN_0, COOLDOWN_1, COOLDOWN_2, COOLDOWN_3, COOLDOWN_4, COOLDOWN_5,
	COOLDOWN_BLOCK, COOLDOWN_IMPALE, COOLDOWN_FORTRESS,
	COOLDOWN_DASH, COOLDOWN_SHURIKEN_THROW, COOLDOWN_CLEANSE
}
