package com.untitled.game.boss1;

/**
 * Enum of Boss1 inputs.
 */
public enum Boss1Input {
	LEFT_KEYDOWN, LEFT_KEYUP, RIGHT_KEYDOWN, RIGHT_KEYUP,
	SLAM_KEYDOWN, SLAM_KEYUP,
	EARTHQUAKE_KEYDOWN, EARTHQUAKE_KEYUP,
	ROLL_KEYDOWN, ROLL_KEYUP,
	CROWD_CONTROL
}
