package com.untitled.assets;

/**
 * Enum of Texture names.
 */
public enum TextureName {
	DEBUFF_STUNNED, DEBUFF_WEAK_SPOT,
	BUTTON_NORMAL, BUTTON_HOVER, BUTTON_MENU_HOVER,
	MENU_BACKGROUND, GAME_BACKGROUND, GAME_FLOOR, GAME_OVERLAY,
	HIGHSCORES_TITLE, HIGHSCORES_ODD, HIGHSCORES_EVEN,
	INFO_BAR_BACKGROUND, HEALTH_BAR_ASSASSIN, HEALTH_BAR_BOSS, HEALTH_BAR_TANK,
	STACK_BAR_ASSASSIN,

	ANDROID_COOLDOWN_0, ANDROID_COOLDOWN_1, ANDROID_COOLDOWN_2, ANDROID_COOLDOWN_3, ANDROID_COOLDOWN_4, ANDROID_COOLDOWN_5,
	ANDROID_COOLDOWN_BLOCK, ANDROID_COOLDOWN_HAMMER_SWING, ANDROID_COOLDOWN_FORTRESS,
	ANDROID_COOLDOWN_DASH, ANDROID_COOLDOWN_SHURIKEN_THROW, ANDROID_COOLDOWN_CLEANSE,
	ANDROID_COOLDOWN_SWITCH_CHARACTER,

	DESKTOP_COOLDOWN_0, DESKTOP_COOLDOWN_1, DESKTOP_COOLDOWN_2, DESKTOP_COOLDOWN_3, DESKTOP_COOLDOWN_4, DESKTOP_COOLDOWN_5,
	DESKTOP_COOLDOWN_BLOCK, DESKTOP_COOLDOWN_HAMMER_SWING, DESKTOP_COOLDOWN_FORTRESS,
	DESKTOP_COOLDOWN_DASH, DESKTOP_COOLDOWN_SHURIKEN_THROW, DESKTOP_COOLDOWN_CLEANSE,
	DESKTOP_COOLDOWN_SWITCH_CHARACTER
}
