package com.untitled.assets;

public enum TextureName {
	DEBUFF_STUNNED, DEBUFF_WEAK_SPOT,
	BUTTON_NORMAL, BUTTON_HOVER, BUTTON_MENU_HOVER,
	MENU_BACKGROUND, GAME_BACKGROUND, GAME_FLOOR, GAME_OVERLAY,
	HIGHSCORES_TITLE, HIGHSCORES_ODD, HIGHSCORES_EVEN,
	INFO_BAR_BACKGROUND, HEALTH_BAR_ASSASSIN, HEALTH_BAR_BOSS, HEALTH_BAR_TANK,
	STACK_BAR_ASSASSIN,
	COOLDOWN_0, COOLDOWN_1, COOLDOWN_2, COOLDOWN_3, COOLDOWN_4, COOLDOWN_5,
	COOLDOWN_BLOCK, COOLDOWN_HAMMER_SWING, COOLDOWN_FORTRESS,
	COOLDOWN_DASH, COOLDOWN_SHURIKEN_THROW, COOLDOWN_CLEANSE,
	COOLDOWN_SWITCH_CHARACTER
}
